""" Add advanced stats fields

Revision ID: 06af9d4ff89b
Revises: cc4a7400b989
Create Date: 2026-07-08 11:49:24.698896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06af9d4ff89b'
down_revision = 'cc4a7400b989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiros_libres_anotados', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('valoracion', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tapones', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('robos', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.drop_column('robos')
        batch_op.drop_column('tapones')
        batch_op.drop_column('valoracion')
        batch_op.drop_column('tiros_libres_anotados')

    # ### end Alembic commands ###
