"""add id_categoria to plantillas

Revision ID: 1959686d785b
Revises: b2c3d4e5f6a7
Create Date: 2026-08-22 18:41:31.998162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1959686d785b'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['id_categoria'], ['id_categoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_categoria')

    # ### end Alembic commands ###
