"""add id_categoria to partido

Revision ID: 3ca0d826dfd3
Revises: 9aebc89fb20d
Create Date: 2026-07-10 10:35:06.830639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca0d826dfd3'
down_revision = '9aebc89fb20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categorias', ['id_categoria'], ['id_categoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_categoria')

    # ### end Alembic commands ###
