"""Migracion inicial

Revision ID: 44112707cbc0
Revises: 
Create Date: 2026-06-07 14:54:00.980704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44112707cbc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.Column('genero_categoria', sa.String(length=20), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('edad_maxima', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("genero_categoria IN ('masculino', 'femenino')", name='ck_categorias_genero'),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('jugadores',
    sa.Column('id_jugador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('documento_identificacion', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('url_foto', sa.Text(), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_jugadores_estado'),
    sa.CheckConstraint("genero IN ('masculino', 'femenino')", name='ck_jugadores_genero'),
    sa.PrimaryKeyConstraint('id_jugador'),
    sa.UniqueConstraint('documento_identificacion')
    )
    op.create_table('patrocinadores',
    sa.Column('id_patrocinador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_patrocinador', sa.String(length=100), nullable=False),
    sa.Column('url_logo_patrocinador', sa.Text(), nullable=True),
    sa.Column('url_imagen_promocional', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_patrocinador')
    )
    op.create_table('torneos',
    sa.Column('id_torneo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('programado', 'en_curso', 'finalizado', 'inactivo')", name='ck_torneos_estado'),
    sa.PrimaryKeyConstraint('id_torneo')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_usuarios_estado'),
    sa.CheckConstraint("rol IN ('super_admin', 'delegado')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('documentacion',
    sa.Column('id_documentacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('url_documento', sa.Text(), nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_documentacion')
    )
    op.create_table('documentos_jugadores',
    sa.Column('id_documentos_jugador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_documento', sa.Text(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('estado_validacion', sa.String(length=20), nullable=False),
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado_validacion IN ('pendiente', 'aprobado', 'rechazado')", name='ck_documentos_jugadores_estado_validacion'),
    sa.CheckConstraint("tipo_documento IN ('cedula', 'certificado_estudios')", name='ck_documentos_jugadores_tipo'),
    sa.ForeignKeyConstraint(['id_jugador'], ['jugadores.id_jugador'], ),
    sa.PrimaryKeyConstraint('id_documentos_jugador')
    )
    op.create_table('equipos',
    sa.Column('id_equipo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_equipo', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('url_logo', sa.Text(), nullable=True),
    sa.Column('url_foto_equipo', sa.Text(), nullable=True),
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_equipos_estado'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.create_table('patrocinadores_torneos',
    sa.Column('id_patrocinador_torneo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_patrocinador', sa.Integer(), nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_patrocinador'], ['patrocinadores.id_patrocinador'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_patrocinador_torneo')
    )
    op.create_table('inscripciones',
    sa.Column('id_inscripcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=False),
    sa.Column('estado_inscripcion', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=10), nullable=True),
    sa.Column('url_comprobante_pago', sa.Text(), nullable=True),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado_inscripcion IN ('pendiente', 'aprobado', 'rechazado')", name='ck_inscripciones_estado'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_inscripcion')
    )
    op.create_table('partidos',
    sa.Column('id_partido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('marcador_local', sa.Integer(), nullable=False),
    sa.Column('marcador_visitante', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=False),
    sa.Column('url_planilla_fiba', sa.Text(), nullable=True),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('id_equipo_local', sa.Integer(), nullable=False),
    sa.Column('id_equipo_visitante', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('programado', 'en_curso', 'finalizado', 'suspendido')", name='ck_partidos_estado'),
    sa.ForeignKeyConstraint(['id_equipo_local'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_equipo_visitante'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_partido')
    )
    op.create_table('plantillas',
    sa.Column('id_plantilla', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_camiseta', sa.Integer(), nullable=True),
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('id_torneo', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'inactivo')", name='ck_plantillas_estado'),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_jugador'], ['jugadores.id_jugador'], ),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneos.id_torneo'], ),
    sa.PrimaryKeyConstraint('id_plantilla')
    )
    op.create_table('estadisticas',
    sa.Column('id_estadistica', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puntos_anotados', sa.Integer(), nullable=False),
    sa.Column('faltas_cometidas', sa.Integer(), nullable=False),
    sa.Column('triples_anotados', sa.Integer(), nullable=False),
    sa.Column('rebotes', sa.Integer(), nullable=False),
    sa.Column('asistencias', sa.Integer(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_jugador'], ['jugadores.id_jugador'], ),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id_partido'], ),
    sa.PrimaryKeyConstraint('id_estadistica')
    )
    op.create_table('sanciones',
    sa.Column('id_sancion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_jugador', sa.Integer(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_jugador'], ['jugadores.id_jugador'], ),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id_partido'], ),
    sa.PrimaryKeyConstraint('id_sancion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanciones')
    op.drop_table('estadisticas')
    op.drop_table('plantillas')
    op.drop_table('partidos')
    op.drop_table('inscripciones')
    op.drop_table('patrocinadores_torneos')
    op.drop_table('equipos')
    op.drop_table('documentos_jugadores')
    op.drop_table('documentacion')
    op.drop_table('usuarios')
    op.drop_table('torneos')
    op.drop_table('patrocinadores')
    op.drop_table('jugadores')
    op.drop_table('categorias')
    # ### end Alembic commands ###
