"""add url_cedula and url_acta_bachiller to jugadores

Revision ID: 5ad3f1c2005d
Revises: 81f7c27c107f
Create Date: 2026-08-01 16:19:12.149114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad3f1c2005d'
down_revision = '81f7c27c107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_cedula', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url_acta_bachiller', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.drop_column('url_acta_bachiller')
        batch_op.drop_column('url_cedula')

    # ### end Alembic commands ###
