"""unificar_nombres_apellidos_en_nombre

Revision ID: 81f7c27c107f
Revises: 3ca0d826dfd3
Create Date: 2026-07-13 07:35:13.332019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f7c27c107f'
down_revision = '3ca0d826dfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=200), nullable=True))
        
    op.execute("UPDATE jugadores SET nombre = nombres || ' ' || apellidos")
    
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.alter_column('nombre', nullable=False)
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
