"""add url_calendario_excel and anulado state

Revision ID: 88b55e00cf32
Revises: 90c623fb3d2a
Create Date: 2026-08-25 13:41:19.876782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b55e00cf32'
down_revision = '90c623fb3d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_calendario_excel', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('ck_torneos_estado', type_='check')
        batch_op.create_check_constraint(
            'ck_torneos_estado',
            "estado IN ('programado', 'en_curso', 'finalizado', 'inactivo', 'anulado')"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.drop_constraint('ck_torneos_estado', type_='check')
        batch_op.create_check_constraint(
            'ck_torneos_estado',
            "estado IN ('programado', 'en_curso', 'finalizado', 'inactivo')"
        )
        batch_op.drop_column('url_calendario_excel')

    # ### end Alembic commands ###
