"""add id_torneo to categoria

Revision ID: 9aebc89fb20d
Revises: d5f7c08ac0fb
Create Date: 2026-07-10 10:06:45.623260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aebc89fb20d'
down_revision = 'd5f7c08ac0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_torneo', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'torneos', ['id_torneo'], ['id_torneo'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_torneo')

    # ### end Alembic commands ###
