"""Add stats indicators to Partido

Revision ID: cc4a7400b989
Revises: a1b2c3d4e5f6
Create Date: 2026-07-04 01:10:29.468896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4a7400b989'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_local_procesadas', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('stats_visitante_procesadas', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_column('stats_visitante_procesadas')
        batch_op.drop_column('stats_local_procesadas')

    # ### end Alembic commands ###
