"""Agregar UniqueConstraint torneo-equipo-categoria en inscripciones

Revision ID: cc4d951950ca
Revises: 44112707cbc0
Create Date: 2026-06-09 11:49:55.660629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4d951950ca'
down_revision = '44112707cbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inscripcion_torneo_equipo_categoria', ['id_torneo', 'id_equipo', 'id_categoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inscripcion_torneo_equipo_categoria', type_='unique')

    # ### end Alembic commands ###
