"""add unique constraint estadistica partido jugador

Revision ID: d5f7c08ac0fb
Revises: 06af9d4ff89b
Create Date: 2026-07-08 15:57:49.517076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f7c08ac0fb'
down_revision = '06af9d4ff89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_estadistica_partido_jugador', ['id_partido', 'id_jugador'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_estadistica_partido_jugador', type_='unique')

    # ### end Alembic commands ###
