"""make genero optional in jugadores

Revision ID: fa545a025869
Revises: 5ad3f1c2005d
Create Date: 2026-08-01 16:30:24.679393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa545a025869'
down_revision = '5ad3f1c2005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
